In [1]:
# Import Libraries needed
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import  RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
# importing our dataset
df = pd.read_csv("KIdney2.csv",index_col=0)

In [4]:
# reading the file
df.head()

Sg   Al   Su  Rbc    Bu   Sc     Sod   Pot  Hemo    Wbcc  Rbcc  Htn  \
Bp                                                                             
80.0  1.020  1.0  0.0  1.0  36.0  1.2  137.53  4.63  15.4  7800.0  5.20  1.0   
50.0  1.020  4.0  0.0  1.0  18.0  0.8  137.53  4.63  11.3  6000.0  4.71  0.0   
80.0  1.010  2.0  3.0  1.0  53.0  1.8  137.53  4.63   9.6  7500.0  4.71  0.0   
70.0  1.005  4.0  0.0  1.0  56.0  3.8  111.00  2.50  11.2  6700.0  3.90  1.0   
80.0  1.010  2.0  0.0  1.0  26.0  1.4  137.53  4.63  11.6  7300.0  4.60  0.0   

      Class  
Bp           
80.0      1  
50.0      1  
80.0      1  
70.0      1  
80.0      1

In [5]:
# Checking missing values
missing_values = df.isnull().sum()
print(missing_values)

Sg       0
Al       0
Su       0
Rbc      0
Bu       0
Sc       0
Sod      0
Pot      0
Hemo     0
Wbcc     0
Rbcc     0
Htn      0
Class    0
dtype: int64


In [6]:
df.describe()

Sg          Al          Su         Rbc         Bu         Sc  \
count  400.000000  400.000000  400.000000  400.000000  400.00000  400.00000   
mean     1.017712    1.015000    0.395000    0.882500   57.40550    3.07235   
std      0.005434    1.272329    1.040038    0.322418   49.28597    5.61749   
min      1.005000    0.000000    0.000000    0.000000    1.50000    0.40000   
25%      1.015000    0.000000    0.000000    1.000000   27.00000    0.90000   
50%      1.020000    1.000000    0.000000    1.000000   44.00000    1.40000   
75%      1.020000    2.000000    0.000000    1.000000   61.75000    3.07000   
max      1.025000    5.000000    5.000000    1.000000  391.00000   76.00000   

              Sod         Pot        Hemo          Wbcc        Rbcc  \
count  400.000000  400.000000  400.000000    400.000000  400.000000   
mean   137.529025    4.627850   12.526900   8406.090000    4.708275   
std      9.204273    2.819783    2.716171   2523.219976    0.840315   
min      4.500000    2.500000    3.100000   2200.000000    2.100000   
25%    135.000000    4.000000   10.875000   6975.000000    4.500000   
50%    137.530000    4.630000   12.530000   8406.000000    4.710000   
75%    141.000000    4.800000   14.625000   9400.000000    5.100000   
max    163.000000   47.000000   17.800000  26400.000000    8.000000   

              Htn       Class  
count  400.000000  400.000000  
mean     0.369350    0.625000  
std      0.482023    0.484729  
min      0.000000    0.000000  
25%      0.000000    0.000000  
50%      0.000000    1.000000  
75%      1.000000    1.000000  
max      1.000000    1.000000

In [7]:
# Correlation
df.corr()

Sg        Al        Su       Rbc        Bu        Sc       Sod  \
Sg     1.000000 -0.460835 -0.292053  0.253894 -0.249263 -0.176141  0.217456   
Al    -0.460835  1.000000  0.262564 -0.374484  0.405035  0.229396 -0.270709   
Su    -0.292053  0.262564  1.000000 -0.092940  0.126074  0.094568 -0.053448   
Rbc    0.253894 -0.374484 -0.092940  1.000000 -0.236270 -0.138391  0.140568   
Bu    -0.249263  0.405035  0.126074 -0.236270  1.000000  0.581176 -0.307357   
Sc    -0.176141  0.229396  0.094568 -0.138391  0.581176  1.000000 -0.624493   
Sod    0.217456 -0.270709 -0.053448  0.140568 -0.307357 -0.624493  1.000000   
Pot   -0.063450  0.114484  0.180098  0.018164  0.336954  0.205361  0.067414   
Hemo   0.492103 -0.548681 -0.156875  0.280991 -0.540699 -0.342053  0.333604   
Wbcc  -0.206880  0.200664  0.159033 -0.002205  0.041530 -0.005420  0.006334   
Rbcc   0.443437 -0.454131 -0.163825  0.202298 -0.465947 -0.323056  0.316883   
Htn   -0.318956  0.478309  0.253179 -0.139342  0.387503  0.273904 -0.306501   
Class -0.659504  0.598389  0.294555 -0.282642  0.371982  0.294076 -0.342268   

            Pot      Hemo      Wbcc      Rbcc       Htn     Class  
Sg    -0.063450  0.492103 -0.206880  0.443437 -0.318956 -0.659504  
Al     0.114484 -0.548681  0.200664 -0.454131  0.478309  0.598389  
Su     0.180098 -0.156875  0.159033 -0.163825  0.253179  0.294555  
Rbc    0.018164  0.280991 -0.002205  0.202298 -0.139342 -0.282642  
Bu     0.336954 -0.540699  0.041530 -0.465947  0.387503  0.371982  
Sc     0.205361 -0.342053 -0.005420 -0.323056  0.273904  0.294076  
Sod    0.067414  0.333604  0.006334  0.316883 -0.306501 -0.342268  
Pot    1.000000 -0.100612 -0.074057 -0.120418  0.057028  0.077063  
Hemo  -0.100612  1.000000 -0.153806  0.681864 -0.576932 -0.729537  
Wbcc  -0.074057 -0.153806  1.000000 -0.151380  0.123790  0.205266  
Rbcc  -0.120418  0.681864 -0.151380  1.000000 -0.527051 -0.590248  
Htn    0.057028 -0.576932  0.123790 -0.527051  1.000000  0.586340  
Class  0.077063 -0.729537  0.205266 -0.590248  0.586340  1.000000

In [8]:
# Separting the data(input and Outcome)
X= df[["Al","Su", "Bu","Sc","Wbcc","Htn"]]
Y = df["Class"]

In [9]:
# Data Standardization
scaler = StandardScaler()

In [10]:
# Fitting the data
scaler.fit(X)
standardized_data = scaler.transform(X)
print(standardized_data)

[[-0.01180416 -0.38026942 -0.43485615 -0.33372463 -0.2405058   1.30997921]
 [ 2.34902872 -0.38026942 -0.80052902 -0.40501999 -0.95477338 -0.76720974]
 [ 0.77514013  2.50785277 -0.08949843 -0.2267816  -0.3595504  -0.76720974]
 ...
 [-0.79874846 -0.38026942 -0.63800774 -0.44066766 -0.71668419 -0.76720974]
 [-0.79874846 -0.38026942 -0.15044391 -0.36937231 -0.47859499 -0.76720974]
 [-0.79874846 -0.38026942 -0.80052902 -0.35154847 -0.63732112 -0.76720974]]


In [11]:
# Storing standardized_data In X variable.
X = standardized_data
Y = df["Class"]

In [12]:
#  Train Test Split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 10)
print(X.shape, X_train.shape, X_test.shape)

(400, 6) (320, 6) (80, 6)


In [13]:
# Train The Model:
classifier = RandomForestClassifier()

In [14]:
# Training the support vector machine  classifier
classifier.fit(X_train, Y_train)

RandomForestClassifier()

In [15]:
# accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print("The accuracy score of the training data:",training_data_accuracy*100)

The accuracy score of the training data: 100.0


In [16]:
# accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print("The accuracy score of the test data:",test_data_accuracy*100)

The accuracy score of the test data: 92.5


In [19]:
# importing Pickle
import pickle
pickle.dump(classifier, open("Kidney.pkl",'wb'))